# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1105, 766)
        Form.setStyleSheet("")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(240, 0, 20, 551))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(310, 20, 731, 471))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.Rename_choice = QtWidgets.QPushButton(self.page)
        self.Rename_choice.setGeometry(QtCore.QRect(90, 80, 191, 41))
        self.Rename_choice.setObjectName("Rename_choice")
        self.replace_radioButton = QtWidgets.QRadioButton(self.page)
        self.replace_radioButton.setGeometry(QtCore.QRect(120, 200, 121, 19))
        self.replace_radioButton.setObjectName("replace_radioButton")
        self.renew_radioButton = QtWidgets.QRadioButton(self.page)
        self.renew_radioButton.setGeometry(QtCore.QRect(120, 240, 141, 19))
        self.renew_radioButton.setObjectName("renew_radioButton")
        self.Rename_start = QtWidgets.QPushButton(self.page)
        self.Rename_start.setGeometry(QtCore.QRect(460, 80, 191, 41))
        self.Rename_start.setObjectName("Rename_start")
        self.Rename_lineEdit = QtWidgets.QLineEdit(self.page)
        self.Rename_lineEdit.setGeometry(QtCore.QRect(400, 200, 241, 21))
        self.Rename_lineEdit.setObjectName("Rename_lineEdit")
        self.Rename_label_4 = QtWidgets.QLabel(self.page)
        self.Rename_label_4.setGeometry(QtCore.QRect(320, 200, 72, 15))
        self.Rename_label_4.setObjectName("Rename_label_4")
        self.Rename_lineEdit_2 = QtWidgets.QLineEdit(self.page)
        self.Rename_lineEdit_2.setGeometry(QtCore.QRect(400, 240, 241, 21))
        self.Rename_lineEdit_2.setObjectName("Rename_lineEdit_2")
        self.Rename_label_5 = QtWidgets.QLabel(self.page)
        self.Rename_label_5.setGeometry(QtCore.QRect(320, 240, 72, 15))
        self.Rename_label_5.setObjectName("Rename_label_5")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(320, 280, 201, 21))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Cut_work = QtWidgets.QPushButton(self.page_2)
        self.Cut_work.setGeometry(QtCore.QRect(100, 285, 151, 41))
        self.Cut_work.setObjectName("Cut_work")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(70, 100, 81, 31))
        self.label.setObjectName("label")
        self.Cut_w = QtWidgets.QLineEdit(self.page_2)
        self.Cut_w.setGeometry(QtCore.QRect(160, 100, 101, 31))
        self.Cut_w.setObjectName("Cut_w")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(400, 45, 211, 21))
        self.label_3.setObjectName("label_3")
        self.Cut_h = QtWidgets.QLineEdit(self.page_2)
        self.Cut_h.setGeometry(QtCore.QRect(160, 180, 101, 31))
        self.Cut_h.setObjectName("Cut_h")
        self.Cut_choice = QtWidgets.QPushButton(self.page_2)
        self.Cut_choice.setGeometry(QtCore.QRect(90, 40, 171, 41))
        self.Cut_choice.setObjectName("Cut_choice")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(70, 180, 81, 31))
        self.label_2.setObjectName("label_2")
        self.Cut_textEdit = QtWidgets.QTextEdit(self.page_2)
        self.Cut_textEdit.setGeometry(QtCore.QRect(320, 80, 371, 251))
        self.Cut_textEdit.setObjectName("Cut_textEdit")
        self.Cut_progressBar = QtWidgets.QProgressBar(self.page_2)
        self.Cut_progressBar.setGeometry(QtCore.QRect(90, 345, 201, 31))
        self.Cut_progressBar.setProperty("value", 24)
        self.Cut_progressBar.setObjectName("Cut_progressBar")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setGeometry(QtCore.QRect(70, 140, 71, 31))
        self.label_18.setObjectName("label_18")
        self.Cut_w_num = QtWidgets.QLineEdit(self.page_2)
        self.Cut_w_num.setGeometry(QtCore.QRect(160, 140, 101, 31))
        self.Cut_w_num.setObjectName("Cut_w_num")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(70, 220, 71, 31))
        self.label_19.setObjectName("label_19")
        self.Cut_h_num = QtWidgets.QLineEdit(self.page_2)
        self.Cut_h_num.setGeometry(QtCore.QRect(160, 220, 101, 31))
        self.Cut_h_num.setObjectName("Cut_h_num")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.conv_radioButton = QtWidgets.QRadioButton(self.page_3)
        self.conv_radioButton.setGeometry(QtCore.QRect(60, 390, 103, 19))
        self.conv_radioButton.setObjectName("conv_radioButton")
        self.pool_radioButton = QtWidgets.QRadioButton(self.page_3)
        self.pool_radioButton.setGeometry(QtCore.QRect(200, 390, 101, 19))
        self.pool_radioButton.setObjectName("pool_radioButton")
        self.conv_pool_calc_pushButton = QtWidgets.QPushButton(self.page_3)
        self.conv_pool_calc_pushButton.setGeometry(QtCore.QRect(470, 60, 151, 41))
        self.conv_pool_calc_pushButton.setObjectName("conv_pool_calc_pushButton")
        self.conv_help_plainTextEdit = QtWidgets.QPlainTextEdit(self.page_3)
        self.conv_help_plainTextEdit.setGeometry(QtCore.QRect(390, 130, 311, 81))
        self.conv_help_plainTextEdit.setObjectName("conv_help_plainTextEdit")
        self.conv_show_plainTextEdit = QtWidgets.QPlainTextEdit(self.page_3)
        self.conv_show_plainTextEdit.setGeometry(QtCore.QRect(390, 240, 311, 131))
        self.conv_show_plainTextEdit.setObjectName("conv_show_plainTextEdit")
        self.layoutWidget = QtWidgets.QWidget(self.page_3)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 60, 281, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.feature_size_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.feature_size_LineEdit.setObjectName("feature_size_LineEdit")
        self.verticalLayout_3.addWidget(self.feature_size_LineEdit)
        self.kernel_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.kernel_LineEdit.setObjectName("kernel_LineEdit")
        self.verticalLayout_3.addWidget(self.kernel_LineEdit)
        self.padding_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.padding_LineEdit.setObjectName("padding_LineEdit")
        self.verticalLayout_3.addWidget(self.padding_LineEdit)
        self.stride_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.stride_LineEdit.setObjectName("stride_LineEdit")
        self.verticalLayout_3.addWidget(self.stride_LineEdit)
        self.dialition_LineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.dialition_LineEdit.setObjectName("dialition_LineEdit")
        self.verticalLayout_3.addWidget(self.dialition_LineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.mean_openfile_pushButton = QtWidgets.QPushButton(self.page_4)
        self.mean_openfile_pushButton.setGeometry(QtCore.QRect(80, 70, 191, 41))
        self.mean_openfile_pushButton.setObjectName("mean_openfile_pushButton")
        self.mean_std_plainTextEdit = QtWidgets.QPlainTextEdit(self.page_4)
        self.mean_std_plainTextEdit.setGeometry(QtCore.QRect(40, 120, 271, 291))
        self.mean_std_plainTextEdit.setObjectName("mean_std_plainTextEdit")
        self.mean_std_calc_pushButton = QtWidgets.QPushButton(self.page_4)
        self.mean_std_calc_pushButton.setGeometry(QtCore.QRect(470, 70, 151, 41))
        self.mean_std_calc_pushButton.setObjectName("mean_std_calc_pushButton")
        self.layoutWidget1 = QtWidgets.QWidget(self.page_4)
        self.layoutWidget1.setGeometry(QtCore.QRect(410, 120, 261, 291))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.Mean_R_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Mean_R_lineEdit.setObjectName("Mean_R_lineEdit")
        self.horizontalLayout_2.addWidget(self.Mean_R_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.Mean_G_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Mean_G_lineEdit.setObjectName("Mean_G_lineEdit")
        self.horizontalLayout_3.addWidget(self.Mean_G_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.Mean_B_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Mean_B_lineEdit.setObjectName("Mean_B_lineEdit")
        self.horizontalLayout_4.addWidget(self.Mean_B_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.Std_R_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Std_R_lineEdit.setObjectName("Std_R_lineEdit")
        self.horizontalLayout_5.addWidget(self.Std_R_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.Std_G_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Std_G_lineEdit.setObjectName("Std_G_lineEdit")
        self.horizontalLayout_6.addWidget(self.Std_G_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.Std_B_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Std_B_lineEdit.setObjectName("Std_B_lineEdit")
        self.horizontalLayout_7.addWidget(self.Std_B_lineEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.Mean_progressBar = QtWidgets.QProgressBar(self.page_4)
        self.Mean_progressBar.setGeometry(QtCore.QRect(40, 430, 641, 23))
        self.Mean_progressBar.setProperty("value", 0)
        self.Mean_progressBar.setObjectName("Mean_progressBar")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.choose_RGB_label_pushButton = QtWidgets.QPushButton(self.page_5)
        self.choose_RGB_label_pushButton.setGeometry(QtCore.QRect(90, 10, 171, 31))
        self.choose_RGB_label_pushButton.setObjectName("choose_RGB_label_pushButton")
        self.line_2 = QtWidgets.QFrame(self.page_5)
        self.line_2.setGeometry(QtCore.QRect(340, 10, 41, 461))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.RGB_label_path_textEdit = QtWidgets.QTextEdit(self.page_5)
        self.RGB_label_path_textEdit.setGeometry(QtCore.QRect(20, 50, 321, 371))
        self.RGB_label_path_textEdit.setObjectName("RGB_label_path_textEdit")
        self.cal_class_and_save_config = QtWidgets.QPushButton(self.page_5)
        self.cal_class_and_save_config.setGeometry(QtCore.QRect(90, 430, 181, 31))
        self.cal_class_and_save_config.setObjectName("cal_class_and_save_config")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.graphicsView_ori_image = QtWidgets.QGraphicsView(self.page_6)
        self.graphicsView_ori_image.setGeometry(QtCore.QRect(10, 30, 256, 192))
        self.graphicsView_ori_image.setObjectName("graphicsView_ori_image")
        self.label_16 = QtWidgets.QLabel(self.page_6)
        self.label_16.setGeometry(QtCore.QRect(100, 10, 61, 16))
        self.label_16.setObjectName("label_16")
        self.graphicsView_tran_image = QtWidgets.QGraphicsView(self.page_6)
        self.graphicsView_tran_image.setGeometry(QtCore.QRect(300, 30, 256, 192))
        self.graphicsView_tran_image.setObjectName("graphicsView_tran_image")
        self.label_17 = QtWidgets.QLabel(self.page_6)
        self.label_17.setGeometry(QtCore.QRect(390, 10, 81, 16))
        self.label_17.setObjectName("label_17")
        self.data_aug_openButton = QtWidgets.QPushButton(self.page_6)
        self.data_aug_openButton.setGeometry(QtCore.QRect(20, 240, 91, 28))
        self.data_aug_openButton.setObjectName("data_aug_openButton")
        self.data_aug_transpose_listWidget = QtWidgets.QListWidget(self.page_6)
        self.data_aug_transpose_listWidget.setGeometry(QtCore.QRect(570, 30, 151, 441))
        self.data_aug_transpose_listWidget.setObjectName("data_aug_transpose_listWidget")
        self.data_aug_startButton = QtWidgets.QPushButton(self.page_6)
        self.data_aug_startButton.setGeometry(QtCore.QRect(450, 240, 91, 28))
        self.data_aug_startButton.setObjectName("data_aug_startButton")
        self.data_aug_showpath_plainTextEdit = QtWidgets.QPlainTextEdit(self.page_6)
        self.data_aug_showpath_plainTextEdit.setGeometry(QtCore.QRect(10, 280, 541, 191))
        self.data_aug_showpath_plainTextEdit.setObjectName("data_aug_showpath_plainTextEdit")
        self.data_aug_add_tran_Button = QtWidgets.QPushButton(self.page_6)
        self.data_aug_add_tran_Button.setGeometry(QtCore.QRect(600, 0, 93, 28))
        self.data_aug_add_tran_Button.setObjectName("data_aug_add_tran_Button")
        self.stackedWidget.addWidget(self.page_6)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 90, 201, 381))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rename = QtWidgets.QPushButton(self.layoutWidget2)
        self.rename.setObjectName("rename")
        self.verticalLayout.addWidget(self.rename)
        self.cut_pic = QtWidgets.QPushButton(self.layoutWidget2)
        self.cut_pic.setObjectName("cut_pic")
        self.verticalLayout.addWidget(self.cut_pic)
        self.conv_pool_calc = QtWidgets.QPushButton(self.layoutWidget2)
        self.conv_pool_calc.setObjectName("conv_pool_calc")
        self.verticalLayout.addWidget(self.conv_pool_calc)
        self.google_transform = QtWidgets.QPushButton(self.layoutWidget2)
        self.google_transform.setObjectName("google_transform")
        self.verticalLayout.addWidget(self.google_transform)
        self.mean_std_calc = QtWidgets.QPushButton(self.layoutWidget2)
        self.mean_std_calc.setObjectName("mean_std_calc")
        self.verticalLayout.addWidget(self.mean_std_calc)
        self.segmentation_label_operation = QtWidgets.QPushButton(self.layoutWidget2)
        self.segmentation_label_operation.setObjectName("segmentation_label_operation")
        self.verticalLayout.addWidget(self.segmentation_label_operation)
        self.data_augmentation = QtWidgets.QPushButton(self.layoutWidget2)
        self.data_augmentation.setObjectName("data_augmentation")
        self.verticalLayout.addWidget(self.data_augmentation)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 530, 1111, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.console_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.console_textBrowser.setGeometry(QtCore.QRect(0, 0, 1101, 211))
        self.console_textBrowser.setObjectName("console_textBrowser")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.Music_pushButton = QtWidgets.QPushButton(Form)
        self.Music_pushButton.setGeometry(QtCore.QRect(80, 30, 93, 28))
        self.Music_pushButton.setObjectName("Music_pushButton")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(4)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Rename_choice.setText(_translate("Form", "选择需要重命名的文件夹"))
        self.replace_radioButton.setText(_translate("Form", "替换原有文件"))
        self.renew_radioButton.setText(_translate("Form", "保存到新的路径"))
        self.Rename_start.setText(_translate("Form", "开始替换"))
        self.Rename_label_4.setText(_translate("Form", "新名字头："))
        self.Rename_label_5.setText(_translate("Form", "新后缀名："))
        self.label_4.setText(_translate("Form", "默认格式： xxx_000001.xxx"))
        self.Cut_work.setText(_translate("Form", "开始切割"))
        self.label.setText(_translate("Form", "切割宽度："))
        self.label_3.setText(_translate("Form", "         待切割图片"))
        self.Cut_choice.setText(_translate("Form", "选择待处理的图片"))
        self.label_2.setText(_translate("Form", "切割高度："))
        self.label_18.setText(_translate("Form", "行图片数："))
        self.label_19.setText(_translate("Form", "列图片数："))
        self.conv_radioButton.setText(_translate("Form", "卷积计算"))
        self.pool_radioButton.setText(_translate("Form", "池化计算"))
        self.conv_pool_calc_pushButton.setText(_translate("Form", "计算"))
        self.conv_help_plainTextEdit.setPlainText(_translate("Form", "帮助文档\n"
"1.如果不是空洞卷积计算，dialition填1\n"
"2.如果是池化计算，dialition填1\n"
""))
        self.label_6.setText(_translate("Form", "输入大小："))
        self.label_8.setText(_translate("Form", "kernel_size："))
        self.label_7.setText(_translate("Form", "padding："))
        self.label_9.setText(_translate("Form", "stride："))
        self.label_10.setText(_translate("Form", "dialition:"))
        self.mean_openfile_pushButton.setText(_translate("Form", "打开数据集所在的文件夹"))
        self.mean_std_calc_pushButton.setText(_translate("Form", "计算均值和方差"))
        self.label_5.setText(_translate("Form", "Mean_R:"))
        self.label_11.setText(_translate("Form", "Mean_G:"))
        self.label_12.setText(_translate("Form", "Mean_B:"))
        self.label_13.setText(_translate("Form", "Std_R:"))
        self.label_14.setText(_translate("Form", "Std_G:"))
        self.label_15.setText(_translate("Form", "Std_B:"))
        self.choose_RGB_label_pushButton.setText(_translate("Form", "选择彩色label图片集"))
        self.cal_class_and_save_config.setText(_translate("Form", "计算类别并保存配置文件"))
        self.label_16.setText(_translate("Form", "原始图片"))
        self.label_17.setText(_translate("Form", "转换后图片"))
        self.data_aug_openButton.setText(_translate("Form", "打开图片"))
        self.data_aug_startButton.setText(_translate("Form", "图像增强"))
        self.data_aug_add_tran_Button.setText(_translate("Form", "添加操作"))
        self.rename.setText(_translate("Form", "批量重命名"))
        self.cut_pic.setText(_translate("Form", "切割图片"))
        self.conv_pool_calc.setText(_translate("Form", "卷积池化计算器"))
        self.google_transform.setText(_translate("Form", "谷歌翻译"))
        self.mean_std_calc.setText(_translate("Form", "求数据集均值和方差"))
        self.segmentation_label_operation.setText(_translate("Form", "语义分割制作标签"))
        self.data_augmentation.setText(_translate("Form", "数据集增强"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.Music_pushButton.setText(_translate("Form", "Music"))

